<?php
/***************************************************************
*  Copyright notice
*  
*  (c) 2004 Rainer Kuhn (kuhn@punkt.de)
*  All rights reserved
*
*  This script is part of the TYPO3 project. The TYPO3 project is 
*  free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
* 
*  The GNU General Public License can be found at
*  http://www.gnu.org/copyleft/gpl.html.
* 
*  This script is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  This copyright notice MUST APPEAR in all copies of the script!
***************************************************************/
/** 
 * Class that adds the wizard icon.
 *
 * @author  (class generated by TYPO3 kickstarter)
 */



class tx_ptgsashop_pi2_wizicon {
    function proc($wizardItems)    {
        global $LANG;

        $LL = $this->includeLocalLang();

        $wizardItems['plugins_tx_ptgsashop_pi2'] = array(
            'icon'=>t3lib_extMgm::extRelPath('pt_gsashop').'pi2/ce_wiz.png',
            'title'=>$LANG->getLLL('pi2_title',$LL),
            'description'=>$LANG->getLLL('pi2_plus_wiz_description',$LL),
            'params'=>'&defVals[tt_content][CType]=list&defVals[tt_content][list_type]=pt_gsashop_pi2'
        );

        return $wizardItems;
    }
    function includeLocalLang()	{
		$llFile = t3lib_extMgm::extPath('pt_gsashop').'locallang.xml';
		$LOCAL_LANG = t3lib_div::readLLXMLfile($llFile, $GLOBALS['LANG']->lang);
					
		return $LOCAL_LANG;
	}
}



if (defined('TYPO3_MODE') && $TYPO3_CONF_VARS[TYPO3_MODE]['XCLASS']['ext/pt_gsashop/pi2/class.tx_ptgsashop_pi2_wizicon.php'])    {
    include_once($TYPO3_CONF_VARS[TYPO3_MODE]['XCLASS']['ext/pt_gsashop/pi2/class.tx_ptgsashop_pi2_wizicon.php']);
}

?>